# docker run --volume "$(pwd):/workspace" --workdir /workspace bufbuild/buf lint

help:
	docker run --volume "${PWD}:/workspace" --workdir /workspace bufbuild/buf --help

lint:
	docker run --volume "${PWD}:/workspace" --workdir /workspace bufbuild/buf lint

# buf --help
# buf build --help
# buf generate --help
# buf breaking --help
# buf lint --help
# buf mod ls-breaking-rules --help
# buf mod ls-lint-rules --help
# buf ls-files --help
